# read about the content here
#   https://docs.docker.com/compose/compose-file/

postgres-zen:
  hostname: postgres-zen
  container_name: postgres-zen
  image: coderdojo/postgres-zen
  command: postgres
  ports: 
    - "5432"
# exposed automatically according to 
#   https://hub.docker.com/_/postgres/
#  expose:
#    - "5432"

zen: 
  hostname: zen
  container_name: zen
  image: coderdojo/zen
  command: bash
  ports: 
    # zen runs on this port
    - "8000:8000"
    # apiBaseUrl
    - "8080:8080"
    # forum 
    - "4567:4567"
  links: 
    - postgres-zen
  volumes:
    - ../code:/user/src/app/cp-local-development
